services:
  devnet:
    image: shardlabs/starknet-devnet-rs:latest
    command: --seed 0 --account-class cairo1
    ports:
      - "5050:5050"
    restart: always

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always

  create-bucket:
    image: quay.io/minio/mc:latest
    depends_on:
      minio:
        condition: service_started
    entrypoint: |
      /bin/sh -c "
        /usr/bin/mc alias set dockerminio http://minio:9000 minioadmin minioadmin
        /usr/bin/mc mb dockerminio/mybucket
        exit 0
      "

  apibara:
    image: quay.io/apibara/starknet:latest
    command: start
    environment:
      - NAME=devnet
      - RPC=http://devnet:5050/rpc
      - WAIT_FOR_RPC=true
      - ADDRESS=0.0.0.0:7171
      - HEAD_REFRESH_INTERVAL_MS=1000
    ports:
      - "7171:7171"
    depends_on:
      devnet:
        condition: service_started
      minio:
        condition: service_started

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/app
    working_dir: /app
    ports:
      - "3000:3000"